
# Agregar su credenciales de mongo atlas

spring:
  data:
    mongodb:
      database: db_ms_order
      uri: mongodb+srv://jeansimon:123@cluster0.a9cmlc1.mongodb.net/?retryWrites=true&w=majority

server:
  port: 8082